### PR TITLE
Update Unit Test and Improve Code Coverage

### PR DESCRIPTION
**Pull request by AsadShakeel**
- created new test cases to improve code coverage
- resolve warning when using generic in Mockito.any()
- added logger instead of using printStackTrace
- fix typos

### CODE REVIEW

**Review by Kaevan89 — APPROVED** [review]
I think all is good, the workflow is falling but it isn't your fault, in fact, the unit test is passing.

**Comment by AsadShakeel** [comment]
It's really great that the changes are accepted.
I believe the issue will be resolved if the same name branch will be created in this repo and upstream is set to it OR update the `Commit and push the badge` job to use the fork repo branch instead of the main repo branch.

**Comment by alejouribesanchez** [comment]
Hi @AsadShakeel could you please update your pull request with the last changes on main branch?, we improved the checks for forked branches so now the check should pass

**Comment by AsadShakeel** [comment]
Hi @alejouribesanchez, the pull request is updated with the latest main branch changes.

**Review by Kaevan89 — APPROVED** [review]

**Review by alejouribesanchez — APPROVED** [review]

**Pull request merged**
